create table tb_historico(
    cod_historico integer generated by default on null as identity primary key,
    cidade VARCHAR2(200) not null,
    data DATE not null,
    link VARCHAR2(500) not null
)

select * from tb_historico